apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    uid: influxdb-plantas
    isDefault: true
    jsonData:
      version: Flux
      organization: proyecto_plantas
      defaultBucket: sensores
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-admin-token
